CREATE TABLE IF NOT EXISTS `cms_arbo` (
  `id_arbo` int(11) NOT NULL auto_increment,
  `id_arbo_pere` int(11) NOT NULL,
  `code_arbo` varchar(64) NOT NULL,
  `famille` varchar(32) NOT NULL default '0',
  `id_pere` int(11) NOT NULL default '0',
  `type_pere` varchar(32) NOT NULL default '',
  `etat` enum('actif','inactif') NOT NULL default 'actif',
  `ordre` int(11) NOT NULL default '0',
  `date_add` varchar(255) NOT NULL default '',
  `date_upd` varchar(255) NOT NULL default '',
  `intitule` varchar(255) NOT NULL default '',
  `intitule_canonize` varchar(255) NOT NULL default '',
  `couleur` varchar(32) NOT NULL default '',
  PRIMARY KEY  (`id_arbo`)
) ENGINE=MyISAM;

#
# Structure de la table `cms_articles`
#

CREATE TABLE IF NOT EXISTS `cms_articles` (
  `id_article` int(11) NOT NULL auto_increment,
  `code` varchar(64) NOT NULL,
  `lang` varchar(64) NOT NULL default '',
  `position_une` int(11) NOT NULL default '0',
  `id_new` varchar(255) NOT NULL default '0',
  `code_news` varchar(255) NOT NULL,
  `position` int(11) NOT NULL,
  `url_image` varchar(255) NOT NULL,
  `contenu` text NOT NULL,
  `image_intro` varchar(255) NOT NULL,
  `date` varchar(255) NOT NULL,
  `texte` text NOT NULL,
  `etat` varchar(32) NOT NULL default '',
  `texte_intro` text NOT NULL,
  `titre_page` varchar(255) NOT NULL,
  `titre` varchar(255) NOT NULL default '',
  `meta_titre` varchar(255) NOT NULL,
  `meta_description` varchar(255) NOT NULL,
  `meta_mots_clefs` varchar(255) NOT NULL,
  `meta_url` varchar(255) NOT NULL,
  `titre_canonize` varchar(255) NOT NULL default '',
  `url_vignette` varchar(255) NOT NULL default '',
  `url_image2` varchar(255) NOT NULL,
  `categorie` varchar(32) NOT NULL default '',
  `titre_data1` varchar(255) NOT NULL,
  `data1` text NOT NULL,
  `titre_data2` varchar(255) NOT NULL,
  `data2` text NOT NULL,
  `titre_data3` varchar(255) NOT NULL,
  `data3` text NOT NULL,
  `titre_data4` varchar(255) NOT NULL,
  `data4` text NOT NULL,
  `titre_data5` varchar(255) NOT NULL,
  `data5` text NOT NULL,
  `titre_data6` varchar(255) NOT NULL,
  `data6` text NOT NULL,
  `titre_data7` varchar(255) NOT NULL,
  `data7` text NOT NULL,
  `titre_data8` varchar(255) NOT NULL,
  `data8` text NOT NULL,
  `titre_data9` varchar(255) NOT NULL,
  `data9` text NOT NULL,
  `titre_data10` varchar(255) NOT NULL,
  `data10` text NOT NULL,
  `titre_data11` varchar(255) NOT NULL,
  `data11` text NOT NULL,
  `titre_data12` varchar(255) NOT NULL,
  `data12` text NOT NULL,
  `titre_data13` varchar(255) NOT NULL,
  `data13` text NOT NULL,
  `titre_data14` varchar(255) NOT NULL,
  `data14` text NOT NULL,
  `titre_data15` varchar(255) NOT NULL,
  `data15` text NOT NULL,
  `titre_data16` varchar(255) NOT NULL,
  `data16` text NOT NULL,
  `titre_data17` varchar(255) NOT NULL,
  `data17` text NOT NULL,
  `titre_data18` varchar(255) NOT NULL,
  `data18` text NOT NULL,
  `titre_data19` varchar(255) NOT NULL,
  `data19` text NOT NULL,
  `titre_data20` varchar(255) NOT NULL,
  `data20` text NOT NULL,
  `titre_fichier1` varchar(255) NOT NULL,
  `fichier1` varchar(255) NOT NULL,
  `titre_fichier2` varchar(255) NOT NULL,
  `fichier2` varchar(255) NOT NULL,
  `titre_fichier3` varchar(255) NOT NULL,
  `fichier3` varchar(255) NOT NULL,
  `titre_fichier4` varchar(255) NOT NULL,
  `fichier4` varchar(255) NOT NULL,
  `titre_fichier5` varchar(255) NOT NULL,
  `fichier5` varchar(255) NOT NULL,
  `id_article_pere` int(11) NOT NULL,
  `previsualisation` int(11) NOT NULL,
  `date_add` varchar(64) NOT NULL default '',
  `date_upd` varchar(64) NOT NULL default '',
  `info_article` varchar(64) NOT NULL default '',
  PRIMARY KEY  (`id_article`),
  KEY `url_vignette` (`url_vignette`)
) ENGINE=MyISAM;
